### PR TITLE
Add mirror links to the GH files for Linux and Windows

### PR DESCRIPTION
**Pull request by pjrobertson**
Right now, if I open the 'desktop' tab on macOS or Linux, I still only see a 'Windows' option there. This adds the option to download the macOS/Linux files via mirror.

Screen Region 2023-11-02 at 22 00 56

Note that this is untested. I am not sure if `{% if..` can go inside a macro.

### CODE REVIEW

**Comment by hiddify-com** [comment]
Thanks for your contribution

We are working on a completly new user page, wait for one week please 😉

**Comment by pjrobertson** [comment]
Great, thank you! I will close this now and check it out in ~1 week.

**Comment by pjrobertson** [comment]
Hey Hiddify, I am re-opening this PR since the user page is still like it was 3 months ago, and this change will help.

It is only a small change, and means downloading files apps on Mac and Linux is much much easier. Thanks!

**Comment by pjrobertson** [comment]
Looks like the new panel has been released 🎉

**Pull request closed without merging**
